"""Offline provider backed by recorded JSON.

Serves two purposes:

* **Tests.** Every criterion can be exercised against a company whose numbers
  are known exactly, so a change in the ROIC maths shows up as a failing
  assertion rather than as a slightly different screen result nobody notices.
* **Reproducible runs.** A fixture set is a frozen snapshot of the inputs, so
  a published result can be regenerated byte-for-byte later -- which a live
  API call can never promise.

The on-disk format mirrors :class:`CompanyFinancials` field for field, so a
fixture can be produced from a live fetch with ``smallcap dump-fixture``.
"""

from __future__ import annotations

import datetime as dt
import glob
import json
import os
from typing import Any, Dict, List, Optional

from ..models import (
    CompanyFinancials,
    FinancialPeriod,
    InsiderHolding,
    InsiderOwnership,
    MarketData,
    PricePoint,
)
from .base import ProviderError


def _date(value: Any) -> Optional[dt.date]:
    if not value:
        return None
    if isinstance(value, dt.date):
        return value
    return dt.date.fromisoformat(str(value)[:10])


def _company_from_dict(raw: Dict[str, Any]) -> CompanyFinancials:
    periods: List[FinancialPeriod] = []
    for entry in raw.get("periods", []):
        data = dict(entry)
        data["end"] = _date(data.get("end"))
        data["filed"] = _date(data.get("filed"))
        allowed = FinancialPeriod.__dataclass_fields__.keys()
        periods.append(FinancialPeriod(**{k: v for k, v in data.items() if k in allowed}))

    market: Optional[MarketData] = None
    raw_market = raw.get("market")
    if raw_market:
        history = [
            PricePoint(date=_date(p["date"]), close=float(p["close"]))
            for p in raw_market.get("history", [])
            if p.get("date") is not None
        ]
        market = MarketData(
            ticker=raw_market.get("ticker", raw.get("ticker", "")),
            price=raw_market.get("price"),
            price_date=_date(raw_market.get("price_date")),
            shares_outstanding=raw_market.get("shares_outstanding"),
            shares_date=_date(raw_market.get("shares_date")),
            market_cap=raw_market.get("market_cap"),
            history=history,
            beta=raw_market.get("beta"),
            currency=raw_market.get("currency", "USD"),
        )
        if market.market_cap is None and market.price and market.shares_outstanding:
            market.market_cap = market.price * market.shares_outstanding

    insiders: Optional[InsiderOwnership] = None
    raw_insiders = raw.get("insiders")
    if raw_insiders:
        holdings = [
            InsiderHolding(
                owner_name=h.get("owner_name", "unknown"),
                owner_cik=h.get("owner_cik"),
                is_officer=bool(h.get("is_officer")),
                is_director=bool(h.get("is_director")),
                is_ten_percent_owner=bool(h.get("is_ten_percent_owner")),
                shares=h.get("shares"),
                as_of=_date(h.get("as_of")),
                source_accession=h.get("source_accession"),
            )
            for h in raw_insiders.get("holdings", [])
        ]
        total = raw_insiders.get("total_shares")
        if total is None and holdings:
            total = sum(h.shares or 0.0 for h in holdings)
        insiders = InsiderOwnership(
            total_shares=total,
            holdings=holdings,
            basis=raw_insiders.get("basis", "form345"),
            as_of=_date(raw_insiders.get("as_of")),
            notes=list(raw_insiders.get("notes", [])),
        )

    return CompanyFinancials(
        ticker=raw["ticker"].upper(),
        cik=raw.get("cik"),
        name=raw.get("name"),
        sic=raw.get("sic"),
        sector=raw.get("sector"),
        exchange=raw.get("exchange"),
        periods=periods,
        market=market,
        insiders=insiders,
        warnings=list(raw.get("warnings", [])),
        source=raw.get("source", "fixture"),
    )


class FixtureProvider:
    """Replays ``*.json`` company snapshots from a directory."""

    name = "fixtures"

    def __init__(self, directory: str = "data/fixtures"):
        self.directory = directory
        self._companies: Optional[Dict[str, CompanyFinancials]] = None

    def _load(self) -> Dict[str, CompanyFinancials]:
        if self._companies is not None:
            return self._companies
        companies: Dict[str, CompanyFinancials] = {}
        pattern = os.path.join(self.directory, "*.json")
        for path in sorted(glob.glob(pattern)):
            with open(path, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
            entries = payload if isinstance(payload, list) else [payload]
            for entry in entries:
                if "ticker" not in entry:
                    continue
                company = _company_from_dict(entry)
                companies[company.ticker] = company
        self._companies = companies
        return companies

    def fetch(
        self, ticker: str, as_of: Optional[dt.date] = None
    ) -> CompanyFinancials:
        companies = self._load()
        company = companies.get(ticker.upper())
        if company is None:
            raise ProviderError(f"{ticker}: no fixture in {self.directory}")
        if as_of is None:
            return company
        return _filter_as_of(company, as_of)

    def universe(self) -> List[str]:
        return sorted(self._load().keys())


def _filter_as_of(company: CompanyFinancials, as_of: dt.date) -> CompanyFinancials:
    """Drop anything that was not public at ``as_of``.

    Fixtures get the same point-in-time treatment as live data; otherwise a
    test would pass on look-ahead data that the live path would reject.
    """
    clone = CompanyFinancials(
        ticker=company.ticker,
        cik=company.cik,
        name=company.name,
        sic=company.sic,
        sector=company.sector,
        exchange=company.exchange,
        periods=[
            p
            for p in company.periods
            if p.end <= as_of and (p.filed is None or p.filed <= as_of)
        ],
        market=company.market,
        insiders=company.insiders,
        warnings=list(company.warnings),
        source=company.source,
    )
    if clone.market and clone.market.history:
        clone.market.history = [p for p in clone.market.history if p.date <= as_of]
    return clone
