"""Offline provider backed by recorded JSON.

Serves two purposes:

* **Tests.** Every criterion can be exercised against a company whose numbers
  are known exactly, so a change in the ROIC maths shows up as a failing
  assertion rather than as a slightly different screen result nobody notices.
* **Reproducible runs.** A fixture set is a frozen snapshot of the inputs, so
  a published result can be regenerated byte-for-byte later -- which a live
  API call can never promise.

The on-disk format mirrors :class:`CompanyFinancials` field for field, so a
fixture can be produced from a live fetch with ``smallcap dump-fixture``.
"""

from __future__ import annotations

import datetime as dt
import glob
import json
import os
from typing import Any, Dict, List, Optional

from ..models import (
    CompanyFinancials,
    FinancialPeriod,
    InsiderHolding,
    InsiderOwnership,
    MarketData,
    PricePoint,
    SharesPoint,
)
from .base import ProviderError


def _date(value: Any) -> Optional[dt.date]:
    if not value:
        return None
    if isinstance(value, dt.date):
        return value
    return dt.date.fromisoformat(str(value)[:10])


def _company_from_dict(raw: Dict[str, Any]) -> CompanyFinancials:
    periods: List[FinancialPeriod] = []
    for entry in raw.get("periods", []):
        data = dict(entry)
        data["end"] = _date(data.get("end"))
        data["filed"] = _date(data.get("filed"))
        allowed = FinancialPeriod.__dataclass_fields__.keys()
        periods.append(FinancialPeriod(**{k: v for k, v in data.items() if k in allowed}))

    market: Optional[MarketData] = None
    raw_market = raw.get("market")
    if raw_market:
        history = [
            PricePoint(date=_date(p["date"]), close=float(p["close"]))
            for p in raw_market.get("history", [])
            if p.get("date") is not None
        ]
        shares_history = [
            SharesPoint(date=_date(s["date"]), shares=float(s["shares"]))
            for s in raw_market.get("shares_history", [])
            if s.get("date") is not None
        ]
        shares_history.sort(key=lambda s: s.date)
        market = MarketData(
            ticker=raw_market.get("ticker", raw.get("ticker", "")),
            shares_history=shares_history,
            price=raw_market.get("price"),
            price_date=_date(raw_market.get("price_date")),
            shares_outstanding=raw_market.get("shares_outstanding"),
            shares_date=_date(raw_market.get("shares_date")),
            market_cap=raw_market.get("market_cap"),
            history=history,
            beta=raw_market.get("beta"),
            currency=raw_market.get("currency", "USD"),
        )
        if market.market_cap is None and market.price and market.shares_outstanding:
            market.market_cap = market.price * market.shares_outstanding

    insiders: Optional[InsiderOwnership] = None
    raw_insiders = raw.get("insiders")
    if raw_insiders:
        holdings = [
            InsiderHolding(
                owner_name=h.get("owner_name", "unknown"),
                owner_cik=h.get("owner_cik"),
                is_officer=bool(h.get("is_officer")),
                is_director=bool(h.get("is_director")),
                is_ten_percent_owner=bool(h.get("is_ten_percent_owner")),
                shares=h.get("shares"),
                as_of=_date(h.get("as_of")),
                source_accession=h.get("source_accession"),
            )
            for h in raw_insiders.get("holdings", [])
        ]
        total = raw_insiders.get("total_shares")
        if total is None and holdings:
            total = sum(h.shares or 0.0 for h in holdings)
        insiders = InsiderOwnership(
            total_shares=total,
            holdings=holdings,
            basis=raw_insiders.get("basis", "form345"),
            as_of=_date(raw_insiders.get("as_of")),
            notes=list(raw_insiders.get("notes", [])),
        )

    return CompanyFinancials(
        ticker=raw["ticker"].upper(),
        cik=raw.get("cik"),
        name=raw.get("name"),
        sic=raw.get("sic"),
        sector=raw.get("sector"),
        exchange=raw.get("exchange"),
        periods=periods,
        market=market,
        insiders=insiders,
        warnings=list(raw.get("warnings", [])),
        source=raw.get("source", "fixture"),
    )


class FixtureProvider:
    """Replays ``*.json`` company snapshots from a directory."""

    name = "fixtures"

    def __init__(self, directory: str = "data/fixtures"):
        self.directory = directory
        self._companies: Optional[Dict[str, CompanyFinancials]] = None

    def _load(self) -> Dict[str, CompanyFinancials]:
        if self._companies is not None:
            return self._companies
        companies: Dict[str, CompanyFinancials] = {}
        pattern = os.path.join(self.directory, "*.json")
        for path in sorted(glob.glob(pattern)):
            with open(path, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
            entries = payload if isinstance(payload, list) else [payload]
            for entry in entries:
                if "ticker" not in entry:
                    continue
                company = _company_from_dict(entry)
                companies[company.ticker] = company
        self._companies = companies
        return companies

    def fetch(
        self, ticker: str, as_of: Optional[dt.date] = None
    ) -> CompanyFinancials:
        companies = self._load()
        company = companies.get(ticker.upper())
        if company is None:
            raise ProviderError(f"{ticker}: no fixture in {self.directory}")
        if as_of is None:
            return company
        return _filter_as_of(company, as_of)

    def universe(self) -> List[str]:
        return sorted(self._load().keys())


def _filter_as_of(company: CompanyFinancials, as_of: dt.date) -> CompanyFinancials:
    """Return a copy of ``company`` holding only what was public at ``as_of``.

    Two things this must get right, both of which are silent if wrong:

    * **The price is rewound too.** Rewinding the filings but leaving today's
      price in place would screen history against a market cap nobody could
      have computed at the time -- look-ahead on the one number you actually
      trade on.
    * **Nothing shared is mutated.** The cached company object is reused for
      every as-of date in a backtest, so trimming its lists in place would let
      an early rebalance date corrupt every later one.
    """
    market = None
    if company.market is not None:
        source = company.market
        history = [p for p in source.history if p.date <= as_of]
        price, price_date = source.price, source.price_date
        if history:
            # The last close on or before the as-of date.
            price, price_date = history[-1].close, history[-1].date
        elif price_date is not None and price_date > as_of:
            # No history to fall back on and the stored quote post-dates the
            # as-of date: report no price rather than a future one.
            price, price_date = None, None
        shares, shares_date = source.shares_outstanding, source.shares_date
        history_shares = [s for s in source.shares_history if s.date <= as_of]
        if history_shares:
            shares, shares_date = history_shares[-1].shares, history_shares[-1].date
        elif shares_date is not None and shares_date > as_of:
            shares, shares_date = None, None
        market = MarketData(
            ticker=source.ticker,
            price=price,
            price_date=price_date,
            shares_outstanding=shares,
            shares_date=shares_date if shares is not None else None,
            market_cap=(price * shares) if (price is not None and shares is not None) else None,
            history=history,
            shares_history=history_shares,
            beta=source.beta,
            currency=source.currency,
        )

    insiders = None
    if company.insiders is not None:
        source_insiders = company.insiders
        holdings = [
            h
            for h in source_insiders.holdings
            if h.as_of is None or h.as_of <= as_of
        ]
        total = (
            sum(h.shares or 0.0 for h in holdings) if holdings else None
        )
        insiders = InsiderOwnership(
            total_shares=total,
            holdings=holdings,
            basis=source_insiders.basis,
            as_of=max(
                (h.as_of for h in holdings if h.as_of), default=None
            ),
            notes=list(source_insiders.notes),
        )

    return CompanyFinancials(
        ticker=company.ticker,
        cik=company.cik,
        name=company.name,
        sic=company.sic,
        sector=company.sector,
        exchange=company.exchange,
        periods=[
            p
            for p in company.periods
            if p.end <= as_of and (p.filed is None or p.filed <= as_of)
        ],
        market=market,
        insiders=insiders,
        warnings=list(company.warnings),
        source=company.source,
    )
